# Generated by Django 6.0.5 on 2026-05-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcription', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('done', 'Completado'), ('error', 'Error')], default='pending', max_length=20)),
            ],
        ),
    ]
