# Generated by Django 6.0.5 on 2026-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='wordcloud_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
