# Generated by Django 6.0.5 on 2026-05-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_wordcloud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completitud_justificacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='completitud_puntaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='glosario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ideas_principales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='preguntas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
